
# This is a basic workflow to help you get started with Actions

name: CI with Java 

# Controls when the workflow will run
on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Checkout our code
        uses: actions/checkout@v2    
      
      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
       # Run our build using Gradle 
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Make a Build Scan
        run: ./gradlew build --scan
